### ISSUE TITLE
rkhunter does not check the kernel

### ISSUE THREAD

**Issue by microlaser** [installation/rkhunter#1]
This is simply a feature request.  Rkhunter would be more effective if I also checked the kernel for malware.  Since the kernel modules are loaded separately from Linux you could check the hash of the kernel in the /boot directory and make sure it is unchanged.  You would have to have it make a network call to pull the right hash, I realize this is asking a lot but it would improve your software because malware can potentially be injected into the kernel by a man-in-the-middle attack for example.

Thank you.

**Comment by sagikazarmark** [comment]
I haven't touched this script in more than 10 years, so it's safe to assume it's unmaintained. Also, this isn't rkhunter, but an installation script.
